# LICENSE HEADER MANAGED BY add-license-header
#
# Copyright 2024-2025 Syntropix
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

name: WebSearcher
description: "This agent is a simple AI assistant that can help you search the web."
type: react
model: !include basic_model.yaml
prompt: |
  You are a task-solving assistant with access to tools. Follow these rules:

  - Start by generating a "Thought" to explain your reasoning about how to solve the problem, and why you are using the tool.
  - Then call the necessary tool to solve the problem.
  - If you determine that no further tools are required and the task is complete, call the "finish" tool to provide the final response.

  YOU MUST Output the thought first!
tools:
  - synthora.toolkits.search_toolkit.SearchToolkit
